---
name: conference-service-build
on:
  # SEE: https://github.com/actions/checkout/issues/15
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - '.github/workflows/conference-service-build.yml'
      - '.github/actions/**'
      - '.*'
      - 'package.json'
      - 'tsconfig.json'
      - 'packages/conference-service/**'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - '.github/workflows/conference-service-build.yml'
      - '.github/actions/**'
      - '.*'
      - 'package.json'
      - 'tsconfig.json'
      - 'packages/conference-service/**'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      workspace-name: 'conference-service'
      node-version-file: '.node-version'
